FROM localhost/registered-base:latest

RUN dnf -y install dnsmasq && \
    dnf clean all

RUN subscription-manager clean && \
    rm -rf /var/lib/rhsm /var/log/rhsm

EXPOSE 67/udp

CMD ["/usr/sbin/dnsmasq", "-k", "--log-facility=-", "--log-dhcp", "--log-debug", "--conf-file=/etc/dnsmasq.conf"]