FROM localhost/registered-base:latest

RUN dnf install -y tftp-server && \
    dnf clean all

RUN subscription-manager clean && \
    rm -rf /var/lib/rhsm /var/log/rhsm

RUN mkdir -p /tftpboot

EXPOSE 69/udp

VOLUME /tftpboot

CMD ["/usr/sbin/in.tftpd", "-L", "-v", "-u", "root", "-s", "/tftpboot"]