FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as python-base

RUN microdnf install python3 python3-pip openssh-clients tar -y && \
    microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /var/log/{dnf,yum}

FROM python-base as ansible-base

RUN mkdir /tmp/{pip,wheels}
ADD ansible.txt /tmp/pip/ansible.txt
WORKDIR /tmp/pip
RUN python3 -m pip wheel --wheel-dir=/tmp/wheels -r ansible.txt

FROM ansible-base as ansible-galaxy

RUN microdnf install findutils krb5-devel gcc python3-devel git -y && \
    microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /var/log/{dnf,yum}

RUN python3 -m pip install --no-cache-dir ansible-core ansible-builder

RUN mkdir -p /tmp/ansible/{roles,collections}

ADD galaxy.cfg /tmp/ansible/galaxy.cfg
ADD requirements.yml /tmp/ansible/requirements.yml
ADD requirements.txt /tmp/pip/requirements.txt

WORKDIR /tmp/ansible
RUN ansible-galaxy collection install -r requirements.yml --collections-path /tmp/ansible/collections
RUN ansible-builder introspect --sanitize /tmp/ansible/collections | sed -n '/^python:/,/^system:/{/^-/{s/^- *'\''//;s/'\''//;s/ *#.*//;s/;.*//;p}}' | { grep -v 'kafka-python-ng\|systemd-python' || :; } > /tmp/pip/pip-install.txt

WORKDIR /tmp/pip
RUN python3 -m pip wheel --no-cache-dir --wheel-dir=/tmp/wheels -r pip-install.txt -r requirements.txt

FROM python-base as openshift-utils
ARG OPENSHIFT_VERSION
RUN curl -o /tmp/openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
RUN tar -xzvf /tmp/openshift-client-linux.tar.gz -C /tmp
RUN chmod +x /tmp/oc
RUN chmod +x /tmp/kubectl
RUN curl -o /tmp/openshift-install-linux.tar.gz "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}/openshift-install-linux.tar.gz"
RUN tar -xzvf /tmp/openshift-install-linux.tar.gz -C /tmp
RUN chmod +x /tmp/openshift-install

FROM ansible-base as execution-environment

RUN mkdir /usr/share/ansible

COPY ansible.cfg /runner/ansible.cfg
COPY --from=ansible-galaxy /tmp/ansible/collections /usr/share/ansible/collections
COPY --from=ansible-base /tmp/pip/ansible.txt /tmp/pip/ansible.txt
COPY --from=ansible-base /tmp/wheels /tmp/wheels
COPY --from=ansible-galaxy /tmp/pip/pip-install.txt /tmp/pip/pip-install.txt
COPY --from=ansible-galaxy /tmp/pip/requirements.txt /tmp/pip/requirements.txt
COPY --from=ansible-galaxy /tmp/wheels /tmp/wheels

WORKDIR /tmp/pip
RUN python -m pip install --no-index --no-cache-dir --find-links=/tmp/wheels -r ansible.txt -r pip-install.txt -r requirements.txt
RUN rm -rf /tmp/wheels /tmp/ansible.txt /tmp/pip-install.txt

COPY --from=openshift-utils /tmp/oc /usr/local/bin/oc
COPY --from=openshift-utils /tmp/kubectl /usr/local/bin/kubectl
COPY --from=openshift-utils /tmp/openshift-install /usr/local/bin/openshift-install

RUN microdnf install nmstate sshpass subscription-manager dnf-utils dnf -y && \
    microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /var/log/{dnf,yum}

RUN mkdir -p /runner/{playbooks,inventory,variables}

RUN mkdir /tmp/pxe-resources
ADD grub.cfg /tmp/pxe-resources/grub.cfg
ADD shimx64.efi /tmp/pxe-resources/shimx64.efi
ADD grubx64.efi /tmp/pxe-resources/grubx64.efi

WORKDIR /runner
LABEL ansible-execution-environment=true
USER 1000

CMD ["bash"]
